# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af2619f19f0c7dca25ae66f45c92b0319a204220a2cab666e9878f8d36a56a39b64744f2d8559e5be5323ac92a512dfd99d94bbcbb77ed74776e08c6c304aab9
  github:
    consumer_key: <%= ENV['GITHUB_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['GITHUB_CONSUMER_SECRET'] %>

test:
  secret_key_base: 129f439088ce1166a6c4925dd0688a432541ba0a49c6234a54ba67a83bbf61742291ef29dbec82dd7a3d91e35d57c39466e70c7a73abb76efb6bc18d2ad424da
  github:
    consumer_key: <%= ENV['GITHUB_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['GITHUB_CONSUMER_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github:
    consumer_key: <%= ENV['GITHUB_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['GITHUB_CONSUMER_SECRET'] %>
